using System;
using System.Collections.Generic;
using System.Text;

namespace Titan.Core.OpenAi
{
    /// <summary>
    /// Represents a message for interaction with the OpenAI service. A message can originate
    /// from the system, a user, an assistant, or a function.
    /// </summary>
    public class OpenAiMessage
    {
        /// <summary>
        /// Gets or sets the role of the message author. This is always one of "system",
        /// "user", "assistant", or "function".
        /// </summary>
        public string Role { get; set; }

        /// <summary>
        /// Gets or sets the text contents of the message. This field is required for all
        /// message types, and may be null for messages from the assistant that include
        /// function calls.
        /// </summary>
        public string Content { get; set; }

        /// <summary>
        /// Gets or sets the name of the author of this message. This field is required if 
        /// this is a function message, and it should be the name of the function that
        /// produced the message content. The name may contain a-z, A-Z, 0-9, and underscores,
        /// and has a maximum length of 64 characters.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the name and arguments of a function call. This property is optional,
        /// and is used when the message represents a function that should be called as
        /// generated by the model's guidance.
        /// </summary>
        public OpenAiFunctionCall FunctionCall { get; set; }
    }
}
